name: Auto Deploy to Linux Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        continue-on-error: true
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 8022
          script_stop: true
          script: |
            cd /home/elontusk/Desktop/PSHomebrew-beta-main
            rm -f serverSettings.json userData.json ticketData.json moderationData.json
            git fetch origin
            git reset --hard origin/main
            sudo systemctl restart discord-bot
            echo "✅ Bot updated and restarted successfully!"
            exit 0
      
      - name: Verify deployment succeeded
        run: echo "✅ Deployment completed successfully!"
